kind: ConfigMap
apiVersion: v1
metadata:
  name: einvoice-frontend-config
  namespace: einvoice-test
data:
  nginx.conf: |
    server {
      listen 8080;
      root /usr/share/nginx/html;
      location / {
         index index.html;
         try_files $uri $uri/ /index.html =404;
      }
    }
